# Generated by Django 3.1.2 on 2020-10-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
